"""Core data structures for the X-Video Engine.

GenerationSpec is the structured request. ReferencePack is the normalized
conditioning input. ShotPlan is the planner output per shot. ExecutionPlan
is the full plan across shots.
"""

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field


# ─── Enums ────────────────────────────────────────────────────────────────

class Mode(str, Enum):
    T2V = "t2v"
    I2V = "i2v"
    FIRST_LAST_FRAME = "first_last_frame"
    REFERENCE_TO_VIDEO = "reference_to_video"
    MULTI_IMAGE_TO_VIDEO = "multi_image_to_video"
    VIDEO_EDIT = "video_edit"
    VIDEO_EXTEND = "video_extend"
    STORYBOARD = "storyboard_to_video"
    CONTROLLED = "controlled"


class BackendName(str, Enum):
    # Phase 1 — AVAILABLE_NOW on RTX 2080 LAN worker
    WAN21_T2V = "wan21_t2v"             # Wan 2.1 T2V-1.3B, ~8GB, native on 2080
    SDXL_IMAGE = "sdxl_image"           # SDXL still generation for first-frame i2v
    # Phase 1+ — Experimental / Future
    WAN22_T2V = "wan22_t2v"
    WAN22_I2V = "wan22_i2v"
    WAN22_TI2V = "wan22_ti2v"
    HUNYUAN15_T2V = "hunyuan15_t2v"
    HUNYUAN15_I2V = "hunyuan15_i2v"
    OMNIWEAVING = "omniweaving"
    LTX_KEYFRAME = "ltx_keyframe"
    LTX_CONTROL = "ltx_control"
    LTX_EXTEND = "ltx_extend"


class ReferenceKind(str, Enum):
    IMAGE = "image"
    VIDEO_CLIP = "video_clip"
    AUDIO_CLIP = "audio_clip"
    KEYFRAME = "keyframe"
    CONTROL_MAP = "control_map"


class ReferenceRole(str, Enum):
    SUBJECT = "subject"
    ENVIRONMENT = "environment"
    STYLE = "style"
    START_FRAME = "start_frame"
    END_FRAME = "end_frame"
    POSE = "pose"
    DEPTH = "depth"
    CANNY = "canny"
    AUDIO_DRIVE = "audio_drive"


class Priority(str, Enum):
    HERO = "hero"
    STANDARD = "standard"
    FILLER = "filler"


# ─── References ───────────────────────────────────────────────────────────

class Reference(BaseModel):
    """A single conditioning input."""
    kind: ReferenceKind
    path: str                                   # local path or s3:// URL
    role: ReferenceRole
    weight: float = Field(default=1.0, ge=0.0, le=2.0)
    metadata: dict = Field(default_factory=dict)


class ReferencePack(BaseModel):
    """Normalized bundle of conditioning inputs for a generation job."""
    items: list[Reference] = Field(default_factory=list)
    preprocessed_manifest: Optional[str] = None   # path to manifest JSON
    clip_embeddings: Optional[str] = None         # path to embeddings file


# ─── Spec building blocks ─────────────────────────────────────────────────

class Camera(BaseModel):
    move: Literal["static", "pan", "push", "pull", "orbit", "handheld", "crane", "dolly"] = "static"
    speed: Literal["slow", "medium", "fast"] = "medium"
    angle: Literal["eye_level", "low", "high", "dutch", "overhead"] = "eye_level"


class Motion(BaseModel):
    subject_motion: Literal["minimal", "moderate", "dynamic"] = "moderate"
    temporal_pacing: Literal["smooth", "staccato"] = "smooth"


class Constraints(BaseModel):
    aspect_ratio: Literal["16:9", "9:16", "1:1", "4:3", "21:9"] = "16:9"
    resolution: Literal["480p", "720p", "1080p"] = "720p"
    fps: Literal[24, 30] = 24
    seed: Optional[int] = None


class AudioIntent(BaseModel):
    ambience: Optional[str] = None
    music: Optional[str] = None
    sfx: list[str] = Field(default_factory=list)
    dialogue: Optional[str] = None


# ─── Top-level spec ───────────────────────────────────────────────────────

class GenerationSpec(BaseModel):
    """Structured user intent. Input to the planner."""
    mode: Mode = Mode.T2V
    subject: str
    action: str = ""
    environment: str = ""
    style: str = ""
    duration_sec: float = Field(default=5.0, gt=0.0, le=60.0)
    camera: Camera = Field(default_factory=Camera)
    motion: Motion = Field(default_factory=Motion)
    references: list[Reference] = Field(default_factory=list)
    constraints: Constraints = Field(default_factory=Constraints)
    audio_intent: AudioIntent = Field(default_factory=AudioIntent)
    raw_prompt: Optional[str] = None             # original user text if compiled


# ─── Planner output ───────────────────────────────────────────────────────

class ShotPlan(BaseModel):
    """A single shot to be generated by one backend."""
    shot_id: str
    backend: BackendName
    mode: Mode
    prompt: str                                  # text prompt for this backend
    negative_prompt: Optional[str] = None
    conditioning: dict = Field(default_factory=dict)   # backend-specific refs
    duration_sec: float
    resolution: Literal["480p", "720p", "1080p"] = "720p"
    fps: Literal[24, 30] = 24
    aspect_ratio: str = "16:9"
    priority: Priority = Priority.STANDARD
    num_candidates: int = 1                      # N takes for reranker
    seed: int = 0


class ExecutionPlan(BaseModel):
    """Full planner output. One or more shots, executed in order."""
    spec_id: str
    shots: list[ShotPlan]
    estimated_cost_usd: float = 0.0
    notes: str = ""


# ─── Results ──────────────────────────────────────────────────────────────

class Take(BaseModel):
    """One candidate generation for a shot."""
    take_id: str
    shot_id: str
    take_number: int
    video_path: str
    seed: int
    backend: BackendName
    generation_time_sec: float = 0.0
    cost_usd: float = 0.0
    score: Optional[float] = None
    scores_detail: dict = Field(default_factory=dict)


class ShotResult(BaseModel):
    """All takes for one shot + the selected winner."""
    shot_id: str
    takes: list[Take]
    winner_take_id: Optional[str] = None
    failure_codes: list[str] = Field(default_factory=list)


class GenerationResult(BaseModel):
    """Final output from the engine."""
    spec_id: str
    plan: ExecutionPlan
    shot_results: list[ShotResult]
    final_video_path: Optional[str] = None
    total_cost_usd: float = 0.0
    total_time_sec: float = 0.0
